// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CollapseTransition: typeof import('./components/transitions/CollapseTransition.vue')['default']
    ContactForm: typeof import('./components/ContactForm.vue')['default']
    ContactUs: typeof import('./components/ContactUs.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FadeTransition: typeof import('./components/transitions/FadeTransition.vue')['default']
    'FadeTransition copy': typeof import('./components/transitions/FadeTransition copy.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    ScrollXTransition: typeof import('./components/transitions/ScrollXTransition.vue')['default']
    SideNavigation: typeof import('./components/SideNavigation.vue')['default']
    SiteInfo: typeof import('./components/SiteInfo.vue')['default']
    Textfield: typeof import('./components/form/textfield.vue')['default']
  }
}

export { }
